#!/usr/bin/env node
// Post-build script to enhance package.json generated by wasm-pack

const fs = require('fs');
const path = require('path');

try {
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '../pkg/package.json'), 'utf8'));
  
  Object.assign(pkg, {
    type: 'module',
    module: pkg.main,
    exports: {
      '.': { types: './rekrypt.d.ts', import: './rekrypt.js', default: './rekrypt.js' },
      './package.json': './package.json'
    },
    bugs: { url: 'https://github.com/stevenleep/rekrypt/issues' },
    engines: { node: '>=16.0.0' },
    publishConfig: { access: 'public' },
    keywords: [
      'cryptography', 'proxy-re-encryption', 'wasm', 'webassembly', 'encryption', 'decryption',
      'security', 'curve25519', 'ecc', 'ecies', 'elliptic-curve', 'rust', 'rustlang',
      'end-to-end-encryption', 'e2ee', 'e2e', 'zero-knowledge', 'privacy',
      'keystore', 'key-management', 'delegation', 'transform-key',
      'symmetric-encryption', 'asymmetric-encryption', 'aes-gcm', 'hybrid-encryption',
      'data-sharing', 'secure-sharing', 'access-control', 'cryptographic-library'
    ]
  });
  
  if (!pkg.files.includes('rekrypt_bg.wasm.d.ts')) pkg.files.push('rekrypt_bg.wasm.d.ts');
  pkg.files.sort();
  
  fs.writeFileSync(path.join(__dirname, '../pkg/package.json'), JSON.stringify(pkg, null, 2) + '\n');
  console.log('[✓] package.json enhanced');
} catch (error) {
  console.error('[ERROR]', error.message);
  process.exit(1);
}

